title: 공간(空間)
meta_title: 공간(空間)
email: kks@gongan.space
description: "단상과 묵상이 있는 공간"
baseurl: ""
url: "https://gongan.space"
hosted_url: ""
github_username: ""
linked_in_profile: ""
full_name: 공간(空間)
user_description: 말씀의 공간, 곧 찾아옵니다.
disqus:
  shortname: jekyll-theme-collider-netlify-com

markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
 
collections:
  blog_posts:
    output: true
    permalink: /collection/:name
  blog_tags:

paginate: 3
paginate_path: /blog/:num/

permalink: pretty

sass:
  sass_dir: _sass

future: true

excerpt_separator: "<!-- more -->"

timezone: Asia/Seoul

host: 0.0.0.0
