title: 공간(空間)
meta_title: Collider Jekyll Theme
email: example@example.com
description: >
  This is the Collider Jekyll Theme.
baseurl: "http://gongan.space"
url: "http://gongan.space"
hosted_url: ""
github_username: ""
linked_in_profile: ""
full_name: 공간(空間)
user_description: 말씀의 공간, 곧 찾아옵니다.
disqus:
  shortname: jekyll-theme-collider-netlify-com

markdown: kramdown
plugins:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  blog_posts:
    output: true
    permalink: /collection/:name
  blog_tags:

pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  collection: 'blog_posts'
  trail:
    before: 2
    after: 2

permalink: pretty

sass:
  sass_dir: _sass

excerpt_separator: "<!-- more -->"
